language: go
go: 
    - 1.14.x
env:
    - GO111MODULE=on
os:
    - linux
script:
    - go mod download
    - go mod vendor
    - go test -v ./...
    - go build -v -o bin/synthesizer cmd/synthesizer/synthesizer.go